# MODULE - SCALAR VECTOR AND MATRIX

#### Scalar

In [1]:
# Define few scalars as follows
number_of_units = 50
mass_of_sun = 1.989e30
length_great_wall_of_china = 21196
print(number_of_units)
print(mass_of_sun)
print(length_great_wall_of_china)

50
1.989e+30
21196


### Vectors
#### Create a column vector

In [1]:
# importing required libraries (numpy as np)
import numpy as np
# creating a column vector with 2 row and 1 columns using np.array() function
col_vec = np.array([[4,5,6,6],[3,6,4,4],[5,555,65,6],[8,8,8,8]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec.shape)

A column vector
 [[  4   5   6   6]
 [  3   6   4   4]
 [  5 555  65   6]
 [  8   8   8   8]]
Shape of vector= (4, 4)


#### Create a row vector


In [14]:
# importing required libraries (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec.shape)

A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


In [4]:
mg_v=np.array([[1,0,0],
               [0,1,0],
               [0,0,1]])
print(mg_v)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
# importing required libraries (numpy as np)
import numpy as np

#Illustrating a Zero vector of dimension 3 using np.array() function
zero_vector_1=np.array([0,0,0])
print(zero_vector_1)

#Illustrating a Zero vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print(zero_vector_2)

#Illustrating a Zero column vector of dimension 3 using np.zeros() function with reshape() function to change the dimensions
zero_vector_3=np.zeros(3).reshape(3,-1)
print(zero_vector_3)

[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [5]:
# importing required libraries (numpy as np)
import numpy as np

#Illustrating a One vector dimension 3 using np.array() function
one_vector_1=np.array([1,1,1])
print(one_vector_1)

#Illustrating a One vector of dimension 3 using np.zeros() function
one_vector_2=np.ones(3)
print(one_vector_2)

#Illustrating a One column vector of dimension 3 using np.zeros() function with reshape() function to change the dimensions
one_vector_3=np.ones(3).reshape(3,-1)
print(one_vector_3)

[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]


In [10]:
# importing required libraries (numpy as np)
import numpy as np
vector=np.array([[4,3,4],[-1,5,3],[2,5,4]])
print("The vector\n",vector)
#Addressing a value of vector by index
print("\nElement at position 1=",vector[0])


The vector
 [[ 4  3  4]
 [-1  5  3]
 [ 2  5  4]]

Element at position 1= [4 3 4]


In [11]:
# importing required libraries (numpy as np)
import numpy as np
#Create a vector
vector=np.array([3,3])
#Magnitude of vector can be found using function np.linalg.norm() function
print("\nMagnitude of the vector = ",np.linalg.norm(vector))



Magnitude of the vector =  4.242640687119285


In [6]:
# importing required libraries (numpy as np)
import numpy as np
vector=np.array([[4],[-1],[2]])
print("The vector\n",vector)

#Addressing a value of vector by index
print("\nElement at position 1=",vector[1])

The vector
 [[ 4]
 [-1]
 [ 2]]

Element at position 1= [-1]


In [7]:
# importing required libraries (numpy as np)
import numpy as np

#Create a vector
vector=np.array([3,3])

#Magnitude of vector can be found using function np.linag.norm() function
print("\nMagnitude of the vector = ",np.linalg.norm(vector))


Magnitude of the vector =  4.242640687119285


#### Matrix

In [8]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2], 
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])

# printing of the matrix and it's dimensions
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)

2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


In [21]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2], 
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])

# printing of the matrix and it's dimensions
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print(np.transpose(matrix_2x2))
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)
td=np.linalg.norm(matrix_3x3)
print(td)


matrix_3x3v2=np.ones(3)
print(matrix_3x3v2)

2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)
[[1 3]
 [2 4]]

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)
18.33030277982336
[1. 1. 1.]


In [9]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])

In [10]:
#selecting an element at row index 2 and column index 1
print("Element of matrix A at index position [2,1] is", A[2,1])

Element of matrix A at index position [2,1] is 4


In [2]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
print("Matrix A:\n",A)

# Finding transpose of a matrix using the function transpose()
print("Matrix A Transpose: \n",np.transpose(A))

Matrix A:
 [[ 2 -2]
 [ 3  1]
 [ 1  4]]
Matrix A Transpose: 
 [[ 2  3  1]
 [-2  1  4]]


In [21]:
zero_vector_3=np.ones(4).reshape(4)
print(zero_vector_3)
print(np.transpose(zero_vector_3))

vect_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vect_1)
print(np.transpose(vect_1))


[1. 1. 1. 1.]
[1. 1. 1. 1.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Diagonal Matrix

In [2]:
# importing required libraries (numpy as np)
import numpy as np
# Creatings a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)

# Creating a diagonal matrix with a range of values
matrix_range= np.diag(np.arange(1,6,2))
print(matrix_range)

[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [46]:
# importing required libraries (numpy as np)
import numpy as np
# Creatings a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)

# Creating a diagonal matrix with a range of values
matrix_range= np.diag(np.arange(1,6,2))
print(matrix_range)
maxt=np.diag(np.arange(1,10,1))
maxt2=np.diag((1,2,3),2)
print(maxt2)

[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]
[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Identity Matrix

In [22]:
# importing required libraries (numpy as np)
import numpy as np
#Creating an Identity matrix of size 2 using np.identity() function
identity_matrix_1 = np.identity(2)
print("Identity_matrix 1\n",identity_matrix_1)

#Creating an Identity matrix of size 3 using np.eye() fucntion
identity_matrix_2 = np.eye(3)
print("\nIdentity_matrix 2\n",identity_matrix_2)

Identity_matrix 1
 [[1. 0.]
 [0. 1.]]

Identity_matrix 2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
identity_matrix_2 = np.identity(5)
print("\nIdentity_matrix 2\n",identity_matrix_2)
print(identity_matrix_2.shape)
print(np.transpose(identity_matrix_2))
identity_matrix_4 = np.identity(3)
print(identity_matrix_4 )
identity_matrix_5 = np.eye(3)
print(identity_matrix_5)




Identity_matrix 2
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Symmetric Matrix

In [14]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix a
a = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("a:\n" , a)

# Finding the Transpose of the matrix
transposed_matrix = a.transpose()
print("Transpose of a:\n" , transposed_matrix)

#Comparing each elements of both matrices (returns a matrix of boolean compared values) and saving it in a varible comparision
comparison = (a == transposed_matrix)

#Checking if all the elements in the matrix comparision is true
equal_arrays = comparison.all()
print(equal_arrays)

a:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
Transpose of a:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True


In [55]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix a
a = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("a:\n" , a)

transposed_mat=a.transpose()
comparison = a==transposed_mat
equal_arrays = comparison.all()
print(equal_arrays)

a:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True


### Triangular Matrix

In [15]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a lower triangular matrix
lower_triangular_matrix_1 = np.tril([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Lower triangular matrix\n",lower_triangular_matrix_1)

Lower triangular matrix
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [38]:
lowerTriangular=np.tril(vect_1)
print(lowerTriangular)
upperTriangular=np.triu(vect_1)
print(upperTriangular)

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [16]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a Upper triangular matrix
upper_triangular_matrix_1 = np.triu([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Upper triangular matrix\n",upper_triangular_matrix_1)

Upper triangular matrix
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


# Exercise

In [79]:
import numpy as np
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat1)
uptr=np.triu(mat1)
print(uptr)
lotr=np.tril(uptr)
print(lotr)
symmat=np.array([[1,2,3],[2,1,4],[3,4,1]])
print(symmat)
symtra= symmat.transpose()
comp= symtra==symmat
chkall=comp.all()
print(chkall)
diamat=np.diag(np.diag(lotr))
print(diamat)

diamat1=

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 2 3]
 [2 1 4]
 [3 4 1]]
True
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [78]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=(np.triu(a))
print(b)
c=np.tril(b)
print(c)
d=np.transpose(c)
print(d)
print(np.diag(c))
e=(c==np.diag(c))
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[1 5 9]
[[ True False False]
 [False  True False]
 [False False  True]]


# MODULE - Operations over vectors and matrices

### Vector Addition

In [91]:
# importing required libraries (numpy as np)
import numpy as np
#Create 2 vectors
vector_1 = np.array([[2, -1, 1]]) 
vector_2 = np.array([[1, 2, -1]])
vect_3=np.array([[10,10,10]])
   
print ("1st  Vector :  ", vector_1)  
print ("2nd  Vector :  ", vector_2)  

# Addition of the vectors using the function np.add()
out = np.add( vector_2, vect_3, vector_2)  
print ("Added Vector : ", out)

1st  Vector :   [[ 2 -1  1]]
2nd  Vector :   [[ 1  2 -1]]
Added Vector :  [[11 12  9]]


### Matrix Addition

In [99]:
# importing required libraries (numpy as np)
import numpy as np
# Creation of 2 matrices
matrix_1 = np.array([[10,20,30],
                     [-30,-40,-50]]) 
matrix_2 = np.array([[100,-200,300],
                     [30,50,70]]) 
mat3=np.array([[-50,-50,-50],
             [10,10,10]])
print ("1st  Matrix : \n", matrix_1)  
print ("2nd  Matrix : \n", matrix_2)  

# Addition of the matrices using np.add() function
out = np.add(matrix_1, matrix_2, mat3)  
print ("Added Matrix : \n", out)

1st  Matrix : 
 [[ 10  20  30]
 [-30 -40 -50]]
2nd  Matrix : 
 [[ 100 -200  300]
 [  30   50   70]]
Added Matrix : 
 [[ 110 -180  330]
 [   0   10   20]]


### Scalar Vector Multiplication

In [105]:
# importing required libraries (numpy as np)
import numpy as np
#Defining a Vector 'v' and scalar 's'
v = np.array([[2],[-1],[3]])
s = 2
#Scalar Vector Multiplication
vector_mul = v*s 
print("Vector: \n",v,"\nScalar:",s,"\nScalar Vector multiplication:\n",vector_mul)

Vector: 
 [[ 2]
 [-1]
 [ 3]] 
Scalar: 2 
Scalar Vector multiplication:
 [[ 4]
 [-2]
 [ 6]]


### Scalar Matrix Multiplication

In [20]:
# importing required libraries (numpy as np)
import numpy as np
#Defining a matrix 'A' and scalar 's'
A = np.array([[1,2,1],
                     [-1,1,0],
                     [2,-1,1]])
print("Matrix:\n",A)
s = 2.5
print("Scalar :",s)

#Scalar Vector Multiplication
matrix_mul =  s * A
print("Scalar Matrix Multiplication:\n",matrix_mul)

Matrix:
 [[ 1  2  1]
 [-1  1  0]
 [ 2 -1  1]]
Scalar : 2.5
Scalar Matrix Multiplication:
 [[ 2.5  5.   2.5]
 [-2.5  2.5  0. ]
 [ 5.  -2.5  2.5]]


### Inner Product

In [33]:
# importing required libraries (numpy as np)
import numpy as np

#Creating the vectors
vector_1 = np.array([1,2,3]) 
vector_2 = np.array([1,0,3]) 
print("Vector 1:\n",vector_1)
print("Vector 2:\n",vector_2)

# Finding inner product of vector of same dimensions using inner() function of the NumPy library.
inner_product_1 = np.inner(vector_1,vector_2)
print("Inner Product of Vector 1, Vector 2:\n",inner_product_1)

Vector 1:
 [1 2 3]
Vector 2:
 [1 0 3]
Inner Product of Vector 1, Vector 2:
 10


In [6]:
import numpy as np
#creating vectors
Vec1=np.array([4,3,-1])
Vec2=np.array([-1,4,8])

resVect= np.inner(Vec1,Vec2)
dotpro= Vec1.dot(Vec2)
print(dotpro)
print(resVect)

0
0


In [8]:
# importing required libraries (numpy as np)
import numpy as np
#Creating the vectors
vector_1 = np.array([1,2,3]) 
vector_2 = np.array([1,0,3]) 
print("Vector 1:\n",vector_1)
print("Vector 2:\n",vector_2)
# Finding inner product of vector of same dimensions using inner() function of the NumPy library.
inner_product_1 = np.inner(vector_1,vector_2)
print("Inner Product of Vector 1, Vector 2:\n",inner_product_1)
dr=vector_1.dot(vector_2)
print(dr)


Vector 1:
 [1 2 3]
Vector 2:
 [1 0 3]
Inner Product of Vector 1, Vector 2:
 10
10


### Difference b/w dot product and inner product

In [10]:
# importing required libraries (numpy as np)
import numpy as np

#Creating vectors
Vector_1 = np.array([[3],[-1],[2]])
Vector_2 = np.array([[2],[4],[-1]])
print("Vector 1\n",Vector_1)
print("Vector 2\n",Vector_2)

#Finding the transpose of Vector_1 
trans = np.transpose(Vector_1)
trn=np.inner(Vector_1,Vector_2)

#Finding the dot product 
result = np.dot(trans,Vector_2)
print("Dot Product\n",result)
print(trn)

Vector 1
 [[ 3]
 [-1]
 [ 2]]
Vector 2
 [[ 2]
 [ 4]
 [-1]]
Dot Product
 [[0]]
[[ 6 12 -3]
 [-2 -4  1]
 [ 4  8 -2]]


### Angle between vector

In [12]:
#import the library numpy
import numpy as np

# Function to find angle between two vectors
def angle_between(vector_1, vector_2):
    dot_pr = vector_1.dot(vector_2)
    norms = np.linalg.norm(vector_1) * np.linalg.norm(vector_2)
     np.arccos
    return np.rad2deg(np.arccos(dot_pr / norms))
# Create two vectors
vector_1 = np.array([3,-1,2])
vector_2 = np.array([2,4,-1]) 

print("v1 = ",vector_1,"\nv2 = ", vector_2)
#Find the angle between them by using the function angle_between()
print("Angle Between the vectors v1 and v2 in 'degree' is :",angle_between(vector_1, vector_2))

v1 =  [ 3 -1  2] 
v2 =  [ 2  4 -1]
Angle Between the vectors v1 and v2 in 'degree' is : 90.0


In [11]:
i

NameError: name 'i' is not defined

In [7]:
#import the library numpy
import numpy as np

#Define a matrix
A =  np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
Av=np.eye(3)
m=np.matmul(A,Av)

print("A :\n", A)
#Define a column vector
#v = np.array([[1,3], [2,3], [3,3]])
#print("v :\n", v)

# Find product of the matrix and Vector
#product = np.matmul(A,v)
#pri=np.matmul(A,v)
#print("Product of A and v is: \n", product)
print(m)

A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Matrix Vector multiplication

### Matrix Multiplication

In [8]:
# importing required libraries (numpy as np)
import numpy as np

# Creating Matrices
A = np.array([[1, 4, 7], 
            [2, 5, 8], 
            [3, 6, 9]])
B = np.array([[4, 2, 3],
            [2, 0, 7],
            [1, 3, 0]])
print("A :\n", A)
print("B :\n", B)

# Multiplying A and B
result=np.matmul(A,B)
print("Matrix Multiplication: A.B :\n",result)

A :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
B :
 [[4 2 3]
 [2 0 7]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Determinant

In [26]:
# importing required libraries (numpy as np)
import numpy as np

# Creating Matrix
matrix = np.array([[10, 2], 
                  [5, 2]])

#Finding the determinant
print(np.linalg.det(matrix))

10.000000000000002


### Matrix Inversion

In [16]:
# Importing required libraries (numpy as np)
import numpy as np

# Creating Matrix A
A = np.array([[1, 2],[4, 5]])

print("Matrix A:\n", A)

# Finding the inverse matrix using np.linalg.inv() function
Ainv = np.linalg.inv(A)
print('The inverse of A is:\n', Ainv)

print("Multiplication of A and Ainv is:\n", np.matmul(A, Ainv))

Matrix A:
 [[1 2]
 [4 5]]
The inverse of A is:
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
Multiplication of A and Ainv is:
 [[1. 0.]
 [0. 1.]]


### Orthogonal Matrix

In [ ]:
Orthogonal Matrix
Consider matrix A of dimension (n, n) where, A is called an Orthogonal matrix if,

A.AT=AT.A=In

where, In is the Identity matrix.

For an orthogonal matrix A,

A-1=AT

Thus, finding inverse is as simple as transposing an orthogonal matrix.

In [28]:
# Importing required libraries (numpy as np)
import numpy as np

# Creating Matrix
A = np.array([[1.0,0.0],
                [0.0,1.0]])

print("A:\n", A)
#Checking for A.AT=AT.A
comparison_1 = np.dot(A.transpose(),A) == np.dot(A,A.transpose())
print(comparison_1)

#Checking for A.AT=Identity Matrix
comparison_2 =  np.dot(A.transpose(),A)== np.eye(2)
print(comparison_2)

# Comparing both the comparison done earlier
comparison_3 = comparison_1 == comparison_2

#Checking if all elements of matrix comparision are true.
equal_arrays = comparison_3.all()
print("A it an orthogonal matrix: ",equal_arrays)

A:
 [[1. 0.]
 [0. 1.]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
A it an orthogonal matrix:  True


### Rank of a Matrix

In [29]:
# Importing required libraries (numpy as np)
import numpy as np

# Creating Matrices
A = np.array([[1,1.0],[3,3]])
print('The matrix A is:\n', A)

B = np.eye(4)

print('The matrix B is:\n', B)


# Finding the rank of matrix a using np.linalg.matrix_rank() function
print(" Rank of A is:",np.linalg.matrix_rank(A))

# Finding the rank of matrix b using np.linalg.matrix_rank() function
print(" Rank of B is:",np.linalg.matrix_rank(B))

The matrix A is:
 [[1. 1.]
 [3. 3.]]
The matrix B is:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank of A is: 1
 Rank of B is: 4


### Exercise

In [52]:
import numpy as np
a1=np.array([[1],[1],[1]])
a2=np.array([[2],[2],[2]])
print(a1," \n", a2)

a1t=np.transpose(a1)
e1=np.dot(a1t,a2)
print(e1)

v1=np.linalg.norm(a1)
v2=np.linalg.norm(a2)
print(v1,v2)
eq2=v1*v2

print(eq2)

[[1]
 [1]
 [1]]  
 [[2]
 [2]
 [2]]
[[6]]
1.7320508075688772 3.4641016151377544
5.999999999999999


In [53]:
import numpy as np
a1=np.array([[1],[1],[1]])
a2=np.array([[1],[3],[1]])
print(a1," \n", a2)

a1t=np.transpose(a1)
e1=np.dot(a1t,a2)
print(e1)

v1=np.linalg.norm(a1)
v2=np.linalg.norm(a2)

eq2=v1*v2

print(eq2)

[[1]
 [1]
 [1]]  
 [[1]
 [3]
 [1]]
[[5]]
5.744562646538029


# Module - Linear Equations

### Solving system of Linear Equations

In [4]:
# import the library numpy 
import numpy as np

#Define the coefficient matrix
matrix_1 = np.array([[1, 3, -1],
              [2, 5, 4],
              [2, 3, -1]])

# Define the vector
matrix_2 = np.array([4,19,7])
# Find the solution system of equations using the solve() method
x= np.linalg.solve(matrix_1, matrix_2)
print("The value of x1 is: ",x[0])
print("The value of x2 is: ",x[1])
print("The value of x3 is: ",x[2])

The value of x1 is:  3.0
The value of x2 is:  1.0
The value of x3 is:  2.0


### Finding Inverse

In [28]:
#import numpy library
import numpy as np

#Create matrix
matrix_1 = np.array([[1, 3, -1],
                      [2, 5, 4],
                      [2, 3, -1]])
matrix_2 = np.array([[3, 4, 4],
                      [2, 3, 9],
                      [2, 2, 5]])
r1=np.linalg.matrix_rank(matrix_2)

print(r1)
#Finding the Inverse of the matrix
print(matrix_2)
mat2inv=np.linalg.inv(matrix_2)
print(mat2inv)
eye=np.matmul(mat2inv,matrix_2)
print(eye)

3
[[3 4 4]
 [2 3 9]
 [2 2 5]]
[[-0.2        -0.8         1.6       ]
 [ 0.53333333  0.46666667 -1.26666667]
 [-0.13333333  0.13333333  0.06666667]]
[[ 1.00000000e+00  0.00000000e+00  1.77635684e-15]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17 -2.77555756e-17  1.00000000e+00]]


In [29]:
# Importing required libraries (numpy as np)
import numpy as np
# Creating Matrix A
A = np.array([[1, 2],
                   [4, 5]])
print("Matrix A:\n", A)
# Finding the inverse matrix using np.linalg.inv() function
Ainv = np.linalg.inv(A)
print('The inverse of A is:\n', Ainv)
print("Multiplication of A and Ainv is:\n", np.matmul(A, Ainv))


Matrix A:
 [[1 2]
 [4 5]]
The inverse of A is:
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
Multiplication of A and Ainv is:
 [[1. 0.]
 [0. 1.]]


singular matrix doesn't have an inverse

In [15]:
import numpy as np
v1=np.array([1,1])
v2=np.array([2,2])
p=v1.dot(v2)
print(p)

v3=np.transpose(v2)
print(v3)
vl1=np.linalg.norm(v1)
vl2=np.linalg.norm(v2)
d=vl1*vl2
print(d)


4
[2 2]
4.000000000000001


In [57]:
np.linalg.norm(vector)
np.rad2deg(np.arccos(dot_pr / norms))
np.linalg.det(matrix)
np.linalg.inv(A)
np.linalg.matrix_rank(A)
x= np.linalg.solve(matrix_1, matrix_2)
x= np.linalg.solve(matrix_1, matrix_2)


NameError: name 'vector' is not defined